# documentation: https://github.com/deltachat/sysadmin/tree/master/delta.chat
name: Delete Preview Deliverables

on: 
  pull_request:
    types: [closed]

jobs:
  delete:

    runs-on: ubuntu-latest

    steps:
    - name: Get Pullrequest ID
      id: getid
      run: |
        export PULLREQUEST_ID=$(jq .number < $GITHUB_EVENT_PATH)
        echo ::set-output name=prid::$PULLREQUEST_ID
    - name: Replace build with error message
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.KEY }}
        USERNAME: ${{ secrets.USERNAME }}
        SERVER_PORT: 22
        FOLDER: ${{ steps.getid.outputs.prid }}
        SERVER_IP: bots.delta.chat
        SERVER_DESTINATION: /var/www/html/staging/
        ARGS: --delete -vhr

